project:
  type: website
  output-dir: docs
  
website:
  title: "iaph2023.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Data Viz"
        menu: 
         - text: "Lisa's Vegetable Garden"
           href: Lisa Vegetable garden.html
         - text: "Carbon Emissions"
           href: Carbon Emissions.html
         - text: "Project 2"
           href: Mini Project 2.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

